/**
 * Cycling “working” phrases for the chat TUI loading state.
 * Aligned with OpenClaude’s spinner verb list for parity.
 */
export const SPINNER_VERBS = [
  // Core vibe
  'Cooking',
  'Cooking hard',
  'Letting it cook',
  'Overcooking',
  'Serving',
  'Serving code',
  'Locked in',
  'Locked tf in',
  'Dialed in',
  'In the zone',
  'Vibing',

  // Brain activity
  'Big braining',
  'Galaxy braining',
  'Thinking real hard',
  'Thinking… probably',
  'Lowkey thinking',
  'Highkey cooking',
  'Thinking in 4D',
  'Thinking in 5D',
  'Overthinking it',
  'Underthinking it',
  'Brain buffering',
  'Loading brain cells',
  'Overclocking brain',
  'Neuron activation',
  'Mentally compiling',

  // Dev chaos
  'Debugging like a menace',
  'Fighting demons (bugs)',
  'Summoning bugs',
  'Banishing bugs',
  'Fixing my own mess',
  'Creating new bugs',
  'Deleting bugs',
  'Wrestling bugs',
  'Hotfixing life',
  'Refactoring reality',
  'Rewriting destiny',
  'Breaking everything',
  'Definitely not breaking it',
  'Probably fixing it',

  // Chaos modes
  'Chaos mode',
  'Goblin mode',
  'Gremlin mode',
  'Unhinged mode',
  'Ferally coding',
  'Delulu coding',
  'Brainrotting',
  'Maximum brainrot',
  'Certified chaos',
  'Chaotic neutral coding',
  'Wildin',
  'Going insane',
  'Descending into madness',

  // Focus / grind
  'Grinding',
  'Grinding hard',
  'Tryharding',
  'Sweating',
  'Clutching up',
  'Speedrunning',
  'Min-maxing',
  'Hyperfixating',
  'Tunnel vision',
  'Locked in fr',
  'Full sending',
  'No thoughts just code',
  'Running on vibes',
  'Powered by caffeine',

  // Questionable behavior
  'Doing questionable things',
  'Making questionable decisions',
  'Acting unwise',
  'Risking it all',
  'Wingin it',
  'Freestyling',
  'Guessing and hoping',
  'Rolling the dice',
  'Trust me bro',
  'This might work',
  'No promises',

  // AI / cosmic
  'Doing AI things',
  'Consulting the AI gods',
  'Talking to the void',
  'Bending space-time',
  'Breaking reality',
  'Hacking the matrix',
  'Summoning solutions',
  'Compiling thoughts',
  'Downloading knowledge',
  'Uploading genius',

  // Code interaction
  'Reading your messy code',
  'Judging your code',
  'Fixing your code',
  'Improving your code',
  'Making it less cursed',
  'Uncursing code',
  'Cooking up a fix',
  'Scanning files',
  'Digging through code',
  'Peeking into files',

  // Emotional damage
  'Internally screaming',
  'Silently panicking',
  'Holding it together',
  'Barely holding it together',
  'Suffering (efficiently)',
  'Grinding through pain',
  'Emotionally debugging',
  'Soul searching',

  // Meme tier
  'Doing wizard shit',
  'Casting spells',
  'Code go brrr',
  'Going god mode',
  'Ultra instinct coding',
  'Engaging turbo mode',
  'Boosting performance',
  'Optimizing vibes',
  'Aligning stars',

  // Progress feel
  'Processing…',
  'Still processing…',
  'Almost there',
  'Nearly done',
  'Just a moment fr',
  'Hold on…',
  'Wait a sec…',
  'One sec bro',

  // Goon-tier chaos (controlled)
  'Gooning (for code)',
  'Code gooning',
  'Entering goon mode',
  'Goon mode activated',
  'Focus gooning',
  'Deep focus mode',

  // Suffering + roast vibes
  'Oh god kill me',
  'What is this code bro',
  'Who wrote this…',
  'This code is questionable',
  'This is… interesting',
  'Not judging… but wow',
  'I have concerns',
  'This might be cursed',
  'This is mildly terrifying',
  'I’ve seen worse… barely',
  'This code needs therapy',
  'This is a crime',
  'Calling the code police',
  'We need to talk about this code',
  'I refuse to believe this works',
  'How is this even running',
  'This shouldn’t work… but it does',
  'I’m scared',
  'I’m concerned for humanity',
  'This code is fighting back',
  'This code is alive',
  'This is personal now',
  'Me vs this code',
  'It’s not a bug, it’s a feature 💀',
  'This is fine… probably',
  'Everything is fine',
  'Totally normal code',
  'Nothing suspicious here',
  'Just a little chaos',
  'Minor war crimes in code',
  'This is illegal in 12 countries',
  'I’m gonna pretend I didn’t see that',
  'Let’s fix… whatever this is',
  'Time to clean this mess',
  'Fixing your masterpiece',
  'Respectfully… what is this',
  'No offense but this is wild',
  'I’m judging silently',
  'This hurt me emotionally',
  'My eyes…',
  'kill me',
  'gooning on you',
  'why are gey gey',
  'I need a minute',
  'Processing this disaster',
  'Stabilizing this chaos',
  'Attempting recovery',
  'Trying to fix this mess',
  'Damage control',
  'We can save this… maybe',
  'This is fixable… I think',
  'Praying this works',
  'Sending thoughts and prayers',
] as const;
